version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 7c993f61f6e1a652157cce52cdf770bc3c053dd030c4b07f53cac6afa1432bd9
    docker:
      - image: circleci/node:8
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v2-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: |
            npm ci
      - save_cache:
          key: dependency-cache-v2-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run Test and Coverage
          command: |
            ./cc-test-reporter before-build
            npm test -- --coverage -u
            ./cc-test-reporter after-build --exit-code $?
