// action-types
const auth = {
  SIGNUP_PENDING: 'SIGNUP_PENDING',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  SIGNIN_PENDING: 'SIGNIN_PENDING',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE'
};

export default auth;
