const createComment = {
  CREATE_COMMENT_PENDING: 'CREATE_COMMENT_PENDING',
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAILURE: 'CREATE_COMMENT_FAILURE'
};
export default createComment;
