const createQuestion = {
  CREATE_QUESTION_PENDING: 'CREATE_QUESTION_PENDING',
  CREATE_QUESTION_SUCCESS: 'CREATE_QUESTION_SUCCESS',
  CREATE_QUESTION_FAILURE: 'CREATE_QUESTION_FAILURE'
};
export default createQuestion;
