const getmeetups = {
  GET_ALL_MEETUPS_PENDING: 'GET_ALL_MEETUPS_PENDING',
  GET_ALL_MEETUPS_SUCCESS: 'GET_ALL_MEETUPS_SUCCESS',
  GET_ALL_MEETUPS_FAILURE: 'GET_ALL_MEETUPS_FAILURE'
};
export default getmeetups;
