const getQuestions = {
  GET_QUESTIONS_PENDING: 'GET_QUESTIONS_PENDING',
  GET_QUESTIONS_SUCCESS: 'GET_QUESTIONS_SUCCESS',
  GET_QUESTIONS_FAILURE: 'GET_QUESTIONS_FAILURE'
};

export default getQuestions;
