const Question = {
  GET_A_QUESTION_PENDING: 'GET_A_QUESTION_PENDING',
  GET_A_QUESTION_SUCCESS: 'GET_A_QUESTION_SUCCESS',
  GET_A_QUESTION_FAILURE: 'GET_A_QUESTION_FAILURE'
};

export default Question;
