const createQuestion = {
  GET_QUESTION_PENDING: 'GET_QUESTION_PENDING',
  GET_QUESTION_SUCCESS: 'GET_QUESTION_SUCCESS',
  GET_QUESTION_FAILURE: 'GET_QUESTION_FAILURE'
};

export default createQuestion;
